### ISSUE TITLE
gamemode 3 (spectator) first person spectate issue

### ISSUE THREAD

**Issue by Maescool** [LilyPad/GoLilyPad#25]
When spectating an entity first person (left clicking it while in gamemode 3)
you can't leave it using "shift" key.

This only happens when you have hopped servers (for example using portalcommand)
this does not happen on the server you initially join.
So when testing this, make sure you hopped.

**Comment by coelho** [comment]
This is likely a plugin channel where we're not swapping the entity id.
I'll look into this. Thanks.
