### ISSUE TITLE
Connect API Query all active servers

### ISSUE THREAD

**Issue by Quicksteve** [LilyPad/GoLilyPad#27]
When managing a server network, it would be nice if there was a way to see which servers are online at the moment (possibly with playercount?).

**Comment by AlfieC** [comment]
This is something the API can offer. Please look into this, it provides useful events such as ServerAddEvent, and once you know the servers on the network you can send a request to find out how many players they have. This is not within the scope of the LilyPad project - so you'll need to develop this by yourself.

**Comment by Quicksteve** [comment]
ServerAddEvent is called when a server connects to the cloud (I would assume). This is not working for my at the moment (probably my own stupidity), but I need to get the current state of the network when the server boots up. How would I go about that?

**Comment by AlfieC** [comment]
Are you sure you're using
`@EventListener` instead of `@EventHandler`?

**Comment by Quicksteve** [comment]
In onEnable:

```java
connect = Bukkit.getServicesManager().getRegistration(Connect.class).getProvider();
connect.registerEvents(this);
```

Same class:

```java
@EventListener
public void serverAdd(ServerAddEvent event) {
    System.out.println("Adding: " + event.getServer());
}

@EventListener
public void serverRemove(ServerRemoveEvent event) {
    System.out.println("Removing: " + event.getServer());
}
```

Starting up or stopping a second server does nothing (both servers are connected and accessible).

**Comment by Quicksteve** [comment]
Solved it by sending a periodic "I am alive" message.
