### ISSUE TITLE
BUG-Lily-pad doesnt provide the correct UUID info on login.

### ISSUE THREAD

**Issue by Eternalrealms** [LilyPad/GoLilyPad#28]
Explanation of Bug:
When my players log into the server it shows the incorrect UUID (Like the server is in offline mode.) If the server is full and players have the permission to bypass the limit it doesn't check their real UUID but an the incorrect one. This happens with anytime I need to check a users UUID on login. This also happens when the server is whit-listed and someone try's to join that is white-listed it will also check the incorrect UUID and tell them they are not white listed. 

The Bug: Lily-pad doesnt provide the correct UUID info on login. 

Version: Bukkit-Connect V87, Go server Proxy V112, Go server connect V57, Spigot 1.8.8 (latest patch)

Errors or Things in the Console: In console it shows when the user logs in it displays the incorrect UUID it checks for X permission under the incorrect UUID then denies the login. Same with whitelist.

Reproduction of Bug: White-list your server add yourself to the white-list (without op) try to join.

Issue occurred when the UUID update happened. Servers are in online mode. When removing lily-pad to test everything worked as it should and displayed the correct UUID.

Thank you for any help!

**Comment by Eternalrealms** [comment]
After the initial login takes place the correct UUID is put into place but its only on server log in that it's an issue.

**Comment by coelho** [comment]
Closing this as I believe this issue is fixed.
