### ISSUE TITLE
1.9 Entity mount issue

### ISSUE THREAD

**Issue by Lmac77** [LilyPad/GoLilyPad#31]
Can climb into a boat just fine on login in the hub server but the minute that you connect to a server on the network and attempt to use a boat, it doesn't interact correctly. It acts like you aren't in the boat but can still click shift and have it give the animation of jumping out of the boat but you are never in the boat.  

Ok, turns out it's impossible to mount any type of entity. Horse, pig, boat, minecart, etc.

**Comment by coelho** [comment]
Version?

**Comment by Lmac77** [comment]
Whoops, forgot about that, my bad. Go-Server-Proxy Build #142 and Go-Server-Connect Build #64 with both being linux-amd64 and on the latest spigot 1.9 build as of 3/5/2016

**Comment by coelho** [comment]
@Lmac77 I'll look into this tomorrow. Thanks for the report :+1:

**Comment by Lmac77** [comment]
No, thank you for the quick response and for all of the work you do. Truly appreciate it and I hope it's an easy fix.

**Comment by Lmac77** [comment]
It seems that with this bug, in your screen it looks like you aren't in the mount and roaming around but other players you just sees you not moving on the mount

**Comment by coelho** [comment]
@Lmac77 The latest commit should fix this :)
