### ISSUE TITLE
Disconnected message instead of proper kick message

### ISSUE THREAD

**Issue by manuelgu** [LilyPad/GoLilyPad#33]
Hello!

Since commit https://github.com/LilyPad/GoLilyPad/commit/97286047228ff35a3ac0e42f35810389eb6831f2 there is a bug in lilypad which makes it so that the kick message which is being sent by the server is not actually showing up in the kick screen. This only occurs if you run 1.9.2 and not 1.9.

![](http://i.imgur.com/qV7XIC2.png)

**Comment by coelho** [comment]
@manuelgu Can you check if a Spigot 1.9.2 server without LilyPad exhibits the same behavior?

**Comment by manuelgu** [comment]
@coelho It works fine on a default Spigot 1.9.2 server

**Comment by manuelgu** [comment]
Any updates? @coelho

**Comment by coelho** [comment]
@manuelgu I haven't had the time to look at this quite yet. I'll do so soon.

**Comment by coelho** [comment]
https://github.com/LilyPad/GoLilyPad/commit/45485b65dade99fd2a72b619e1a21d139557e149
Should fix it?

**Comment by manuelgu** [comment]
Yes, fixed! Thanks :+1:
