### ISSUE TITLE
Skins aren't working

### ISSUE THREAD

**Issue by WitherSkeletons** [LilyPad/GoLilyPad#34]
Hello,
I am currently using the newest versions of the Connect and Proxy. Skins are not showing on any of my servers.

**Comment by coelho** [comment]
Spigot version?

**Comment by WitherSkeletons** [comment]
Sorry for a delayed response, my spigot version is PaperSpigot 1.8.8

**Comment by coelho** [comment]
I believe you may be running the 1.9 Bukkit-Connect? Try downgrading to:
http://ci.lilypadmc.org/job/Bukkit-Connect/95/

**Comment by WitherSkeletons** [comment]
Ok, I will try this when I have some time this evening. Thank you for a prompt response

**Comment by WitherSkeletons** [comment]
Yup that did the trick. Thank you for your help!
