### ISSUE TITLE
Player data not working

### ISSUE THREAD

**Issue by Lmac77** [LilyPad/GoLilyPad#35]
I've updated to Minecraft 1.9.4 and it seems that everytime a player goes to Hub or disconnects, the players inventory resets, removing everything they had and treating the player like a new player by not saving the players data file. Been using proxy version #148 and bukkit-connect #98.

**Comment by WitherSkeletons** [comment]
This is more than likely a server end issue being that LilyPad does not affect player/uuid files

**Comment by coelho** [comment]
Yeah this would be more of a Bukkit-Connect bug but this place is fine as well. I haven't heard of this bug before, I'll need to test it.

**Comment by Lmac77** [comment]
I'm sorry, I wasn't sure what it would fall under so I posted it here. Lilypad servers were the only ones experiencing this issue even on servers with no other plugins. I'll try to give more info if needed.

**Comment by WitherSkeletons** [comment]
Posting a log of your console after player join/leave might help coelho

**Comment by Lmac77** [comment]
Okie dokie, will try that right away.

**Comment by WitherSkeletons** [comment]
Upload it to a site - it will make it easier for people to read

**Comment by Lmac77** [comment]
http://pastebin.com/gUxnGUUB
Link to the Hub server console log.
Did you want the logs for the proxy and connect as well?

**Comment by Lmac77** [comment]
If anything else is needed just let me know. I've been triple checking everything to try and verify if it's something wrong on my end but sadly have come up with nothing.

**Comment by manuelgu** [comment]
I can confirm this bug. Fresh install of spigot 1.9.4 and BukkitConnect.

**Comment by manuelgu** [comment]
This seems to be an issue with the playerdata files. `OfflinePlayer#hasPlayedBefore` returns false after the upgrade when the join for the first time.

@coelho Any clue?

**Comment by manuelgu** [comment]
After further investigation it turns out that the `playerdata/uuid.dat` files itself are stored properly.

1. Move to somewhere else, put item in your inventory and log off.
2. Inspect .dat file and see that location and inventory is stored
3. Login again
4. Inspect .dat file again, location and inventory is still stored
5. Log off
6. Inspect .dat file once more, see empty inventory and default location

**Comment by coelho** [comment]
I'll review this more in a few days. I think I have an idea of what it is.

**Comment by fatboy2380** [comment]
I think I've been experiencing a similar if not the same issue where when I log in for the first time (new uuid.dat file) I spawn correctly, but when I log out, it will always spawn me back at that position when I log  in.

**Comment by Maescool** [comment]
So I've been looking into the code
1.8 UserCache
`public UserCache(MinecraftServer minecraftserver, File file) {`
1.9 and up:
`public UserCache(GameProfileRepository gameprofilerepository, File file) {`

So, my guess is Bukkit-Connect, LoginListener, usercache part needs to be updated

**Comment by coelho** [comment]
Please check if the latest LilyPad-Connect fixes this?

**Comment by manuelgu** [comment]
This has been fixed and can be closed.
