### ISSUE TITLE
File corruption on Jenkins

### ISSUE THREAD

**Issue by manuelgu** [LilyPad/GoLilyPad#40]
`wget http://ci.lilypadmc.org/job/Go-Server-Proxy/lastStableBuild/artifact/target/proxy-linux-amd64`

resuls in
![](http://i.imgur.com/NudFE0N.png) running in an infinite loop

Adding the file in a docker context also breaks
![](http://i.imgur.com/Wlahz6Z.png)

**Comment by coelho** [comment]
@manuelgu Should be resolved. Disk filled up.
