### ISSUE TITLE
GoLilyPad vs JLilyPad

### ISSUE THREAD

**Issue by lukechatton** [LilyPad/GoLilyPad#43]
Are there any outstanding differences between GoLilyPad and JLilyPad? Is there any reason to prefer JLilyPad over GoLilyPad other than wanting to stick with Java?

**Comment by coelho** [comment]
JLilyPad is the original implementation of LilyPad that is no longer maintained besides:
- Bukkit-Connect
- Client-Connect-Lib
- Client-Connect-API
- Packet-Common
- Packet-Connect
.. basically enough necessary for the Bukkit plugin to work.

Besides that, GoLilyPad is today's Connect server and Proxy server that is fully updated and has the most compatibility.

Does that explain well?

**Comment by lukechatton** [comment]
That makes perfect sense. Thank you for the clarification!
