### ISSUE TITLE
Proxy is version 1.11.2 when self-building

### ISSUE THREAD

**Issue by dordsor21** [LilyPad/GoLilyPad#44]
Using a fork, with network leave/join events, merged all latest commits into fork, when following build instructions the proxy still comes up as 1.11.2 in Minecraft game

**Comment by dordsor21** [comment]
https://github.com/dordsor21/GoLilyPad

**Comment by coelho** [comment]
This has to do with Golang's build caching if I recall correctly and I have no clue how to fix it myself. Just set a different GOPATH?

**Comment by dordsor21** [comment]
Managed to make it work with resetting everything goLang
