### ISSUE TITLE
Possible issue with using Fireworks to go faster with the Elytra

### ISSUE THREAD

**Issue by HyKurtis** [LilyPad/GoLilyPad#51]
Hey. 

So, I recently switched to GoLilyPad from BungeeCord and after I made the switch I realised that firework rockets were no longer making elytra flight faster. 

I didn't assume this was an issue with GoLilyPad until I searched google to find this used to be an issue in BungeeCord before it was patched. Here is the commit in BungeeCord where they fixed the issue: https://github.com/SpigotMC/BungeeCord/commit/6104354fa1a87a8a09d852ef8ec388611a9b51f1

Here is the thread where I found out it used to be an issue in BungeeCord: https://www.spigotmc.org/threads/fireworks-not-boosting-elytra.206316/

I'm assuming using a proxy stops them from working, but BungeeCord was able to patch it, so could a similar patch be added to GoLilyPad to resolve the issue? 

If this can be fixed that would be great as a lot of players on my server want this back and if it's an issue with the proxy there isn't much I can do about it. 

Thanks!

**Comment by jordanwilliams1** [comment]
@HyKurtis Was this ever fixed?

**Comment by HyKurtis** [comment]
@jordanwilliams1 I don't believe so.

**Comment by coelho** [comment]
Never had the chance to fix this. May look into it next week.

**Comment by jordanwilliams1** [comment]
@coelho I Hope you do 👍 I Recently changed from bungee to LilyPad and I haven't regretted it one bit. I Hope this gets resolved.

**Comment by jordanwilliams1** [comment]
@coelho Update?

**Comment by jordanwilliams1** [comment]
@coelho Please? i don't want to go back to bungee 😭

**Comment by Yive** [comment]
Any updates on this issue? It has been a full year and not supporting this packet really affects gameplay to the point where I had to add in a plugin with a hacky fix for it.

**Comment by Yive** [comment]
Managed to get around to testing this bug, turns out you can actually boost while wearing elytras with fireworks... but the proxy needs to be hosted on windows.

Tried with a build from before the packet & swap entities rewrite, both have this strange issue. Sadly I don't know Golang so can't really pinpoint what's causing this issue.

**Comment by alexmarkey** [comment]
Still waiting patiently for this fix :)

**Comment by jordanwilliams1** [comment]
I had to switch back to bungee ;( Maybe one day It'll be fixed.

**Comment by Yive** [comment]
Done some more testing, here is how you recreate the issue.

1. Start up a proxy with a direct connect to server A
2. Connect through the direct connect to server A, attempt to fly around with elytra and rockets. You'll notice it works.
3. Use a plugin that will send you to server B, do the exact same and it will not work.

This is not an issue with linux so this is a problem with the redirection system.

**Comment by coelho** [comment]
This is fixed in 1.16+.
