### ISSUE TITLE
Maven goal error when building my project

### ISSUE THREAD

**Issue by VicenteRD** [LilyPad/GoLilyPad#52]
While building a project, I get a Maven error for `lilypad.client.connect`:

```[ERROR] Failed to execute goal on project DiscordConnect: Could not resolve dependencies for project <>: The following artifacts could not be resolved: lilypad.client.connect:lib:jar:0.0.1-SNAPSHOT, lilypad.packet:connect:jar:0.0.1-SNAPSHOT, lilypad.packet:common:jar:0.0.1-SNAPSHOT: Could not transfer artifact lilypad.client.connect:lib:jar:0.0.1-20171001.001814-50 from/to lilypad (http://ci.lilypadmc.org/plugin/repository/everything): GET request of: lilypad/client/connect/lib/0.0.1-SNAPSHOT/lib-0.0.1-20171001.001814-50.jar from lilypad failed: Premature end of Content-Length delimited message body (expected: 4324897; received: 15679 -> [Help 1]```

I tried a second time thinking the connection might've gotten interrupted, got the same error except `expected: 4324897; received: 15439`

Is this on my side or yours?

**Comment by coelho** [comment]
Should be fixed.

**Comment by VicenteRD** [comment]
Thank you!

**Comment by coelho** [comment]
Should be fixed, again @VicenteRD -- it's an issue with the box holding the site where the disk fills up every now and then.

**Comment by VicenteRD** [comment]
Wow, that was fast!
Thanks for letting me know :)
