### ISSUE TITLE
issue with using Fireworks to go faster with the Elytra

### ISSUE THREAD

**Issue by jordanwilliams1** [LilyPad/GoLilyPad#53]
Hey.

So, I recently switched to GoLilyPad from BungeeCord and after I made the switch I realised that firework rockets were no longer making elytra flight faster.

I didn't assume this was an issue with GoLilyPad until I searched google to find this used to be an issue in BungeeCord before it was patched. Here is the commit in BungeeCord where they fixed the issue: SpigotMC/BungeeCord@6104354

Here is the thread where I found out it used to be an issue in BungeeCord: https://www.spigotmc.org/threads/fireworks-not-boosting-elytra.206316/

I'm assuming using a proxy stops them from working, but BungeeCord was able to patch it, so could a similar patch be added to GoLilyPad to resolve the issue?

If this can be fixed that would be great as a lot of players on my server want this back and if it's an issue with the proxy there isn't much I can do about it.

Thanks!

**Comment by coelho** [comment]
This is fixed in 1.16+.
