### ISSUE TITLE
 trouble connecting

### ISSUE THREAD

**Issue by jordanwilliams1** [LilyPad/GoLilyPad#54]
Alot of my players are having problems connecting to my other servers? They enter the hub and try to connect to a server and just get kicked.

"Update: My game no longer loads the main server. It goes straight to "Loading terrain..." and then crashes after a minute of not being able to connect."

**Comment by jordanwilliams1** [comment]
Here's my proxy.yml
https://pastebin.com/raw/dTwa3XFN

I Did want everyone to connect to the hub then use towny.differentcraft.net to direct connect to "towny" but it doesn't seem to listen to my proxy.yml so i just pointed everything to towny and removed my "hub" server because people keep crashing when they try to go from the hub to towny.

**Comment by coelho** [comment]
@jordanwilliams1 Unfortunately this can't be an issue with LilyPad. I'd check to make sure your host/Spigot is not having any issues.
