### ISSUE TITLE
Locales are not being detected when client joins server

### ISSUE THREAD

**Issue by midnjerry** [LilyPad/GoLilyPad#55]
In Spigot, Player Locale can be detected with Player.getLocale().  When connecting to a host Spigot server behind LilyPad, Player.getLocale() ALWAYS returns "en_us" upon player joining.  Player.getLocale() still returns "en_us" for players using "es_mx" locale.

To verify that it's a LilyPad issue, I used ProtocolLib.

1. Launch spigot server (1.12.2) (accept eula and let it generate a world)
2. Copy ProtocolLib.jar to /plugins directory and restart server.
3. In console type: **packet add client 21 true** (this listens for packet _PacketPlayInSettings_  This packet is sent by the Minecraft client and has updated locale settings for the player)
4. Connect to running server with a Minecraft client
5. Look at log you will see something similar to this:

`[ProtocolLib] Received SETTINGS[class=PacketPlayInSettings, id=5] from BigMacMC:
{ a = "es_mx", b = 32, c =Unknown macro: { e = 0, f = "options.chat.visibility.full", name = "FULL", ordinal = 0 }
, d = true, e = 127, f = { c = ("TextComponent{text='Right', siblings=[], style=Style{hasParent=false, color=null, bold=false, italic=false, underlined=false, obfuscated=false, clickEvent=null, hoverEvent=null, insertion=null}}"), name = "RIGHT", ordinal = 1 } }`

The host was able to detect my locale as "es_mx" (look at **a = "es_mx"**).  

I setup LilyPad so that it points to same Server.  I then repeated the above steps.  When connecting to the LilyPad ip, I successfully joined the server but DID NOT SEE packet _PacketPlayInSettings_ being captured.  When executing Player.getLocale(), the result returned was "en_us" even though I was using locale "es_mx".  

If as a player I changed my locale while playing (hitting Escape to go to menu, Options->Language->Espanol(Mexico)), the server would successfully detect the new locale change of "es_mx" and the console would display multiple packets of _PacketPlayInSettings_ with the correct locale information being captured.

However, if I disconnected and reconnected, I would never see packet _PacketPlayInSettings_ being captured.  When calling Player.getLocale() I would get "en_us".

it seems packet _PacketPlayInSettings_ is being blocked by LilyPad for new players joining, but not blocked for any other events where the client transmits the packet.

**Comment by coelho** [comment]
@midnjerry Is this after a redirect or is this the first server you're connecting to on LilyPad?

**Comment by coelho** [comment]
Also, what is your client version?

**Comment by GrimTheReaper** [comment]
@midnjerry Are you still experiencing this issue?

**Comment by coelho** [comment]
Closing this issue as it does not occur in my tests.
