### ISSUE TITLE
Large scoreboard.dat on 1.16.4 causes players to hang on the "Loading terrain..." screen

### ISSUE THREAD

**Issue by WesJD** [LilyPad/GoLilyPad#67]
Recently we switched from 1.13.2 to 1.16.4, and after about two weeks, servers started to be completely unjoinable and left players hanging on the "Loading terrain..." screen. After many hours of debugging, we have found that if the `scoreboard.dat` world data file is >1mb in size on 1.16.4 the issue occurs. When testing without running behind the proxy, the client can connect fine. 

We know that this issue must have some relation to 1.16 of the sort, as we have found hubs with 5mb `scoreboard.dat` files that are running on 1.12 without issue in the past. Even if the issue is just some sort of limitation, it'd be best to at least disconnect the player with an error, as this caused many hours of headaches.

**Comment by coelho** [comment]
This issue is pretty common and also to my knowledge occurs with Bungeecord networks. No real resolution for this and this is more of a Minecraft bug that it is sending scoreboard data it does not need to send.
